# Generated by Django 4.0 on 2021-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0005_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
