# Generated by Django 4.0 on 2021-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0006_remove_customer_id_alter_customer_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.IntegerField(default=0),
        ),
    ]
